USE DATABASE FROSTYFRIDAY;
CREATE SCHEMA IF NOT EXISTS WEEKLYCHALLENGES;
USE SCHEMA CHALLENGES;

CREATE OR REPLACE STAGE S3_FF_WEEK1
    URL = 's3://frostyfridaychallenges/challenge_1/';
    
-- SHOW STAGES;

CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT
TYPE='CSV'
FIELD_DELIMITER=',';

-- SHOW FILE FORMATS;

-- SELECT DISTINCT METADATA$FILENAME AS FILENAME
-- FROM @S3_FF_WEEK1;

-- see results
SELECT  $1 AS RESULT
FROM @S3_FF_WEEK1
(FILE_FORMAT => 'CSV_FORMAT');

-- create table
CREATE TABLE IF NOT EXISTS CHALLENGES.WEEK1 (RESULT TEXT);

--load the data
COPY INTO CHALLENGES.WEEK1
FROM (
    SELECT  $1
    FROM @S3_FF_WEEK1
    (FILE_FORMAT => 'CSV_FORMAT')
);

SELECT * FROM FROSTYFRIDAY.CHALLENGES.WEEK1;
