USE DATABASE FROSTYFRIDAY;
USE SCHEMA CHALLENGES;

CREATE OR REPLACE STAGE S3_FF_WEEK3
    URL = 's3://frostyfridaychallenges/challenge_3/';
    
-- SHOW STAGES;

-- SELECT DISTINCT METADATA$FILENAME AS FILENAME
-- FROM @S3_FF_WEEK3;

-- csv file format with header row
CREATE FILE FORMAT IF NOT EXISTS CSV_FORMAT_H1
TYPE='CSV'
FIELD_DELIMITER=','
SKIP_HEADER = 1;

-- check keywords.csv contents
SELECT  $1
FROM @S3_FF_WEEK3/keywords.csv
(FILE_FORMAT => 'CSV_FORMAT_H1');

-- place the keywords in a temp table
CREATE OR REPLACE TEMPORARY TABLE KEYWORDS_TMP (KEYWORD VARCHAR);

COPY INTO KEYWORDS_TMP
FROM (
    SELECT $1 FROM @S3_FF_WEEK3/keywords.csv
    (FILE_FORMAT => 'CSV_FORMAT_H1')
);
SELECT * FROM KEYWORDS_TMP;


SELECT array_agg(KEYWORD) FROM KEYWORDS_TMP;


-- Create the table to store the metadata
CREATE OR REPLACE TABLE WEEK3 (
  FILE_NAME VARCHAR,
  NUMBER_OF_ROWS NUMBER,
  LAST_MODIFIED TIMESTAMP
);

-- add the data to the table
INSERT INTO WEEK3 (FILE_NAME, NUMBER_OF_ROWS, LAST_MODIFIED)
SELECT METADATA$FILENAME AS FILE_NAME, COUNT(FILE_NAME) AS NUMBER_OF_ROWS, METADATA$FILE_LAST_MODIFIED AS LAST_MODIFIED
FROM @S3_FF_WEEK3
    (FILE_FORMAT => 'CSV_FORMAT_H1')
WHERE EXISTS (
    SELECT 1 FROM KEYWORDS_TMP WHERE METADATA$FILENAME LIKE '%' || KEYWORD || '%'
  )
GROUP BY FILE_NAME, LAST_MODIFIED
ORDER BY NUMBER_OF_ROWS ASC;

SELECT * FROM WEEK3;
